import { englishScenes } from "./story.en.ts";
import { scenes as germanScenes } from "./story.ts";

export type PresentationLocale = "de" | "en";

export const presentationCopy = {
  de: {
    locale: "de",
    scenes: germanScenes,
    title: "Oki und die vielen Inseln",
    subtitle: "Der illustrierte Kinderführer zu OpenKubes",
    edition: "Digitale HTML-Ausgabe · v1.2",
    coverIntro:
      "Eine Geschichte über klare Versprechen, ehrliche Beweise und Menschen, die Verantwortung übernehmen.",
    sceneCount: "18 Szenen",
    language: "Deutsch",
    languageCode: "EN",
    languageHref: "/en/",
    languageLabel: "Englische Ausgabe öffnen",
    sceneLabel: "Szene",
    canonicalIllustration: "Kanonische Illustration",
    quoteEyebrow: "Der Leitgedanke",
    quoteTitle: "In einer Familie darf jeder anders sein.",
    quoteBody: "Sie hält zusammen, weil sich alle aufeinander verlassen können.",
    quoteNote:
      "Nicht ein bestimmtes Werkzeug verbindet die Inseln, sondern gemeinsam verstandene Versprechen.",
    finaleEyebrow: "Was ist OpenKubes?",
    finaleTitle: "Eine gute Art, immer wieder verlässliche Inseln zu bauen.",
    finaleRhythm: "Baue. Verbinde. Prüfe. Lerne. Wachse.",
    finaleSmall:
      "Nicht eine einzige Insel. Eine gemeinsame Methode für viele unterschiedliche Plattformen.",
    aboutEyebrow: "Weiter entdecken",
    aboutTitle: "Eine Insel entsteht. Dann noch eine.",
    aboutQuestion: "Aber wann ist sie nicht nur da, sondern wirklich verlässlich?",
    license:
      "Text und Konzept: OpenKubes Community. Illustrationen: CC BY 4.0; OpenKubes/Oki-Namen, Logos und Marken ausgenommen.",
    startLabel: "Start",
    quoteLabel: "Leitgedanke",
    finaleLabel: "OpenKubes",
    aboutLabel: "Weiter entdecken",
    presentationAria: "Oki und die vielen Inseln – HTML-Präsentation",
    slideAnnouncement: "Folie",
    of: "von",
    menu: "Übersicht",
    menuOpen: "Folienübersicht öffnen",
    menuClose: "Folienübersicht schließen",
    menuTitle: "Folienübersicht",
    menuAria: "Präsentationssteuerung",
    previous: "Vorherige Folie",
    next: "Nächste Folie",
    fullscreenStart: "Vollbild starten",
    fullscreenEnd: "Vollbild beenden",
    fullscreen: "Vollbild",
    window: "Fenster",
    keyboardHint: "← → navigieren · M Übersicht · F Vollbild",
  },
  en: {
    locale: "en",
    scenes: englishScenes,
    title: "Oki and the Many Islands",
    subtitle: "The Illustrated Children’s Guide to OpenKubes",
    edition: "English HTML Preview · v1.0 RC1",
    coverIntro:
      "A story about clear promises, honest evidence, and people who take responsibility.",
    sceneCount: "18 scenes",
    language: "English",
    languageCode: "DE",
    languageHref: "/",
    languageLabel: "Open the German edition",
    sceneLabel: "Scene",
    canonicalIllustration: "Canonical illustration",
    quoteEyebrow: "The central idea",
    quoteTitle: "Everyone in a family can be different.",
    quoteBody: "The family stays together because they can rely on one another.",
    quoteNote:
      "The islands are connected by promises they understand together—not by one particular tool.",
    finaleEyebrow: "What is OpenKubes?",
    finaleTitle: "A good way to build reliable islands again and again.",
    finaleRhythm: "Build. Connect. Verify. Learn. Grow.",
    finaleSmall:
      "Not a single island. A shared method for many different platforms.",
    aboutEyebrow: "Keep exploring",
    aboutTitle: "One island emerges. Then another.",
    aboutQuestion: "But when is it not merely there, but truly reliable?",
    license:
      "Text and concept: OpenKubes Community. Illustrations: CC BY 4.0; OpenKubes/Oki names, logos, and trademarks excluded.",
    startLabel: "Start",
    quoteLabel: "Central idea",
    finaleLabel: "OpenKubes",
    aboutLabel: "Keep exploring",
    presentationAria: "Oki and the Many Islands – HTML presentation",
    slideAnnouncement: "Slide",
    of: "of",
    menu: "Overview",
    menuOpen: "Open slide overview",
    menuClose: "Close slide overview",
    menuTitle: "Slide overview",
    menuAria: "Presentation controls",
    previous: "Previous slide",
    next: "Next slide",
    fullscreenStart: "Enter fullscreen",
    fullscreenEnd: "Exit fullscreen",
    fullscreen: "Fullscreen",
    window: "Window",
    keyboardHint: "← → navigate · M overview · F fullscreen",
  },
} as const;

export type PresentationCopy = (typeof presentationCopy)[PresentationLocale];
