import { englishScenes } from "./story.en.ts";
import { spanishScenes } from "./story.es.ts";
import { persianScenes } from "./story.fa.ts";
import { chineseScenes } from "./story.zh.ts";
import { japaneseScenes } from "./story.ja.ts";
import { scenes as germanScenes } from "./story.ts";

export type PresentationLocale = "de" | "en" | "es" | "fa" | "zh" | "ja";

export const languageOptions: Array<{
  locale: PresentationLocale;
  code: string;
  label: string;
  href: string;
}> = [
  { locale: "de", code: "DE", label: "Deutsch", href: "/" },
  { locale: "en", code: "EN", label: "English", href: "/en/" },
  { locale: "es", code: "ES", label: "Español", href: "/es/" },
  { locale: "fa", code: "فا", label: "فارسی", href: "/fa/" },
  { locale: "zh", code: "中文", label: "简体中文", href: "/zh/" },
  { locale: "ja", code: "日本語", label: "日本語", href: "/ja/" },
];

const creationCredit = {
  creator: "Created by Arash Kaffamanesh for Kubernauts",
  assistance: "with assistance from ChatGPT and Codex",
} as const;

export const presentationCopy = {
  de: {
    locale: "de",
    direction: "ltr",
    scenes: germanScenes,
    title: "Oki und die vielen Inseln",
    subtitle: "Der illustrierte Kinderführer zu OpenKubes",
    edition: "Digitale HTML-Ausgabe · v1.2",
    coverIntro:
      "Eine Geschichte über klare Versprechen, ehrliche Beweise und Menschen, die Verantwortung übernehmen.",
    creationCredit,
    sceneCount: "18 Szenen",
    language: "Deutsch",
    languageMenuLabel: "Sprache wählen",
    sceneLabel: "Szene",
    canonicalIllustration: "Kanonische Illustration",
    quoteEyebrow: "Der Leitgedanke",
    quoteTitle: "In einer Familie darf jeder anders sein.",
    quoteBody: "Sie hält zusammen, weil sich alle aufeinander verlassen können.",
    quoteNote:
      "Nicht ein bestimmtes Werkzeug verbindet die Inseln, sondern gemeinsam verstandene Versprechen.",
    finaleEyebrow: "Was ist OpenKubes?",
    finaleTitle: "Eine gute Art, immer wieder verlässliche Inseln zu bauen.",
    finaleRhythm: "Baue. Verbinde. Prüfe. Lerne. Wachse.",
    finaleSmall:
      "Nicht eine einzige Insel. Eine gemeinsame Methode für viele unterschiedliche Plattformen.",
    aboutEyebrow: "Weiter entdecken",
    aboutTitle: "Eine Insel entsteht. Dann noch eine.",
    aboutQuestion: "Aber wann ist sie nicht nur da, sondern wirklich verlässlich?",
    license:
      "Text und Konzept: OpenKubes Community. Illustrationen: CC BY 4.0; OpenKubes/Oki-Namen, Logos und Marken ausgenommen.",
    startLabel: "Start",
    quoteLabel: "Leitgedanke",
    finaleLabel: "OpenKubes",
    aboutLabel: "Weiter entdecken",
    presentationAria: "Oki und die vielen Inseln – HTML-Präsentation",
    slideAnnouncement: "Folie",
    of: "von",
    menu: "Übersicht",
    menuOpen: "Folienübersicht öffnen",
    menuClose: "Folienübersicht schließen",
    menuTitle: "Folienübersicht",
    menuAria: "Präsentationssteuerung",
    previous: "Vorherige Folie",
    next: "Nächste Folie",
    fullscreenStart: "Vollbild starten",
    fullscreenEnd: "Vollbild beenden",
    fullscreen: "Vollbild",
    window: "Fenster",
    keyboardHint: "← → navigieren · M Übersicht · F Vollbild",
  },
  en: {
    locale: "en",
    direction: "ltr",
    scenes: englishScenes,
    title: "Oki and the Many Islands",
    subtitle: "The Illustrated Children’s Guide to OpenKubes",
    edition: "English HTML Preview · v1.0 RC1",
    coverIntro:
      "A story about clear promises, honest evidence, and people who take responsibility.",
    creationCredit,
    sceneCount: "18 scenes",
    language: "English",
    languageMenuLabel: "Choose language",
    sceneLabel: "Scene",
    canonicalIllustration: "Canonical illustration",
    quoteEyebrow: "The central idea",
    quoteTitle: "Everyone in a family can be different.",
    quoteBody: "The family stays together because they can rely on one another.",
    quoteNote:
      "The islands are connected by promises they understand together—not by one particular tool.",
    finaleEyebrow: "What is OpenKubes?",
    finaleTitle: "A good way to build reliable islands again and again.",
    finaleRhythm: "Build. Connect. Verify. Learn. Grow.",
    finaleSmall:
      "Not a single island. A shared method for many different platforms.",
    aboutEyebrow: "Keep exploring",
    aboutTitle: "One island emerges. Then another.",
    aboutQuestion: "But when is it not merely there, but truly reliable?",
    license:
      "Text and concept: OpenKubes Community. Illustrations: CC BY 4.0; OpenKubes/Oki names, logos, and trademarks excluded.",
    startLabel: "Start",
    quoteLabel: "Central idea",
    finaleLabel: "OpenKubes",
    aboutLabel: "Keep exploring",
    presentationAria: "Oki and the Many Islands – HTML presentation",
    slideAnnouncement: "Slide",
    of: "of",
    menu: "Overview",
    menuOpen: "Open slide overview",
    menuClose: "Close slide overview",
    menuTitle: "Slide overview",
    menuAria: "Presentation controls",
    previous: "Previous slide",
    next: "Next slide",
    fullscreenStart: "Enter fullscreen",
    fullscreenEnd: "Exit fullscreen",
    fullscreen: "Fullscreen",
    window: "Window",
    keyboardHint: "← → navigate · M overview · F fullscreen",
  },
  es: {
    locale: "es",
    direction: "ltr",
    scenes: spanishScenes,
    title: "Oki y las muchas islas",
    subtitle: "La guía infantil ilustrada de OpenKubes",
    edition: "Vista previa HTML en español · v1.0 RC1",
    coverIntro:
      "Una historia sobre promesas claras, evidencia honesta y personas que asumen responsabilidades.",
    creationCredit,
    sceneCount: "18 escenas",
    language: "Español",
    languageMenuLabel: "Elegir idioma",
    sceneLabel: "Escena",
    canonicalIllustration: "Ilustración canónica",
    quoteEyebrow: "La idea central",
    quoteTitle: "En una familia, cada uno puede ser diferente.",
    quoteBody: "La familia permanece unida porque todos pueden confiar unos en otros.",
    quoteNote:
      "Las islas están conectadas por promesas que comprenden juntas, no por una herramienta concreta.",
    finaleEyebrow: "¿Qué es OpenKubes?",
    finaleTitle: "Una buena manera de construir islas confiables una y otra vez.",
    finaleRhythm: "Construye. Conecta. Comprueba. Aprende. Crece.",
    finaleSmall:
      "No es una sola isla. Es un método compartido para muchas plataformas diferentes.",
    aboutEyebrow: "Sigue explorando",
    aboutTitle: "Aparece una isla. Después, otra.",
    aboutQuestion: "Pero ¿cuándo deja de estar simplemente ahí y se vuelve realmente confiable?",
    license:
      "Texto y concepto: OpenKubes Community. Ilustraciones: CC BY 4.0; se excluyen los nombres, logotipos y marcas de OpenKubes/Oki.",
    startLabel: "Inicio",
    quoteLabel: "Idea central",
    finaleLabel: "OpenKubes",
    aboutLabel: "Sigue explorando",
    presentationAria: "Oki y las muchas islas – presentación HTML",
    slideAnnouncement: "Diapositiva",
    of: "de",
    menu: "Índice",
    menuOpen: "Abrir el índice de diapositivas",
    menuClose: "Cerrar el índice de diapositivas",
    menuTitle: "Índice de diapositivas",
    menuAria: "Controles de la presentación",
    previous: "Diapositiva anterior",
    next: "Diapositiva siguiente",
    fullscreenStart: "Activar pantalla completa",
    fullscreenEnd: "Salir de pantalla completa",
    fullscreen: "Pantalla completa",
    window: "Ventana",
    keyboardHint: "← → navegar · M índice · F pantalla completa",
  },
  fa: {
    locale: "fa",
    direction: "rtl",
    scenes: persianScenes,
    title: "اوکی و جزیره‌های بسیار",
    subtitle: "راهنمای مصور کودکان برای OpenKubes",
    edition: "پیش‌نمایش HTML فارسی · v1.0 RC1",
    coverIntro:
      "داستانی دربارهٔ قول‌های روشن، مدرک‌های صادقانه و انسان‌هایی که مسئولیت می‌پذیرند.",
    creationCredit,
    sceneCount: "۱۸ صحنه",
    language: "فارسی",
    languageMenuLabel: "انتخاب زبان",
    sceneLabel: "صحنه",
    canonicalIllustration: "تصویر رسمی",
    quoteEyebrow: "اندیشهٔ اصلی",
    quoteTitle: "در یک خانواده هرکس می‌تواند متفاوت باشد.",
    quoteBody: "خانواده کنار هم می‌ماند، چون همه می‌توانند به یکدیگر اعتماد کنند.",
    quoteNote:
      "جزیره‌ها با قول‌هایی که همه با هم می‌فهمند پیوند دارند، نه با یک ابزار مشخص.",
    finaleEyebrow: "OpenKubes چیست؟",
    finaleTitle: "راهی خوب برای ساختن دوباره و دوبارهٔ جزیره‌های قابل اعتماد.",
    finaleRhythm: "بساز. پیوند بده. بررسی کن. یاد بگیر. رشد کن.",
    finaleSmall:
      "نه یک جزیرهٔ تنها؛ روشی مشترک برای پلتفرم‌های گوناگون.",
    aboutEyebrow: "بیشتر بدانید",
    aboutTitle: "یک جزیره پدیدار می‌شود. سپس یکی دیگر.",
    aboutQuestion: "اما چه زمانی فقط آنجا نیست و واقعاً قابل اعتماد است؟",
    license:
      "متن و ایده: OpenKubes Community. تصاویر: CC BY 4.0؛ نام‌ها، نشان‌ها و علامت‌های تجاری OpenKubes/Oki مستثنا هستند.",
    startLabel: "آغاز",
    quoteLabel: "اندیشهٔ اصلی",
    finaleLabel: "OpenKubes",
    aboutLabel: "بیشتر بدانید",
    presentationAria: "اوکی و جزیره‌های بسیار – ارائهٔ HTML",
    slideAnnouncement: "اسلاید",
    of: "از",
    menu: "فهرست",
    menuOpen: "باز کردن فهرست اسلایدها",
    menuClose: "بستن فهرست اسلایدها",
    menuTitle: "فهرست اسلایدها",
    menuAria: "کنترل‌های ارائه",
    previous: "اسلاید پیشین",
    next: "اسلاید بعدی",
    fullscreenStart: "ورود به تمام‌صفحه",
    fullscreenEnd: "خروج از تمام‌صفحه",
    fullscreen: "تمام‌صفحه",
    window: "پنجره",
    keyboardHint: "برای جابه‌جایی ← → · M فهرست · F تمام‌صفحه",
  },
  zh: {
    locale: "zh",
    direction: "ltr",
    scenes: chineseScenes,
    title: "奥奇和许许多多的岛屿",
    subtitle: "OpenKubes 儿童图解指南",
    edition: "简体中文 HTML 审校预览 · v1.0 RC1",
    coverIntro:
      "一个关于清楚的承诺、诚实的证据，以及勇于承担责任的人们的故事。",
    creationCredit,
    sceneCount: "18 个场景",
    language: "简体中文",
    languageMenuLabel: "选择语言",
    sceneLabel: "场景",
    canonicalIllustration: "正式插图",
    quoteEyebrow: "核心想法",
    quoteTitle: "一家人可以各不相同。",
    quoteBody: "大家能够彼此依靠，所以始终在一起。",
    quoteNote:
      "连接岛屿的不是某一种工具，而是大家共同理解的承诺。",
    finaleEyebrow: "什么是 OpenKubes？",
    finaleTitle: "一种能一次又一次建造可靠岛屿的好办法。",
    finaleRhythm: "建造。连接。验证。学习。成长。",
    finaleSmall:
      "它不是某一座岛，而是许多不同平台共同使用的一种方法。",
    aboutEyebrow: "继续探索",
    aboutTitle: "一座岛出现了，接着又出现一座。",
    aboutQuestion: "可它什么时候才不只是存在，而是真正可靠呢？",
    license:
      "文字与构思：OpenKubes Community。插图：CC BY 4.0；OpenKubes/Oki 的名称、标志和商标除外。",
    startLabel: "开始",
    quoteLabel: "核心想法",
    finaleLabel: "OpenKubes",
    aboutLabel: "继续探索",
    presentationAria: "奥奇和许许多多的岛屿 – HTML 演示",
    slideAnnouncement: "幻灯片",
    of: "共",
    menu: "目录",
    menuOpen: "打开幻灯片目录",
    menuClose: "关闭幻灯片目录",
    menuTitle: "幻灯片目录",
    menuAria: "演示控制",
    previous: "上一张幻灯片",
    next: "下一张幻灯片",
    fullscreenStart: "进入全屏",
    fullscreenEnd: "退出全屏",
    fullscreen: "全屏",
    window: "窗口",
    keyboardHint: "← → 翻页 · M 目录 · F 全屏",
  },
  ja: {
    locale: "ja",
    direction: "ltr",
    scenes: japaneseScenes,
    title: "オキとたくさんの島々",
    subtitle: "OpenKubes の子ども向けイラストガイド",
    edition: "日本語 HTML レビュー版 · v1.0 RC1",
    coverIntro:
      "分かりやすい約束、正直な証拠、そして責任を引き受ける人々の物語。",
    creationCredit,
    sceneCount: "18 シーン",
    language: "日本語",
    languageMenuLabel: "言語を選ぶ",
    sceneLabel: "シーン",
    canonicalIllustration: "公式イラスト",
    quoteEyebrow: "大切な考え",
    quoteTitle: "家族は、みんな違っていていい。",
    quoteBody: "おたがいを頼りにできるから、一緒にいられます。",
    quoteNote:
      "島々をつなぐのは特定の道具ではなく、みんなで理解する約束です。",
    finaleEyebrow: "OpenKubes とは？",
    finaleTitle: "信頼できる島を何度でも作るための、よい方法。",
    finaleRhythm: "作る。つなぐ。確かめる。学ぶ。育つ。",
    finaleSmall:
      "ひとつの島ではありません。さまざまなプラットフォームのための共通の方法です。",
    aboutEyebrow: "もっと知ろう",
    aboutTitle: "ひとつの島が生まれ、また次の島が生まれる。",
    aboutQuestion: "でも、ただそこにあるだけでなく、本当に信頼できるのはいつ？",
    license:
      "文章と構想：OpenKubes Community。イラスト：CC BY 4.0。OpenKubes/Oki の名称、ロゴ、商標は対象外です。",
    startLabel: "スタート",
    quoteLabel: "大切な考え",
    finaleLabel: "OpenKubes",
    aboutLabel: "もっと知ろう",
    presentationAria: "オキとたくさんの島々 – HTML プレゼンテーション",
    slideAnnouncement: "スライド",
    of: "中",
    menu: "一覧",
    menuOpen: "スライド一覧を開く",
    menuClose: "スライド一覧を閉じる",
    menuTitle: "スライド一覧",
    menuAria: "プレゼンテーション操作",
    previous: "前のスライド",
    next: "次のスライド",
    fullscreenStart: "全画面にする",
    fullscreenEnd: "全画面を終了",
    fullscreen: "全画面",
    window: "ウィンドウ",
    keyboardHint: "← → 移動 · M 一覧 · F 全画面",
  },
} as const;

export type PresentationCopy = (typeof presentationCopy)[PresentationLocale];
