export type StoryScene = {
  number: number;
  slug: string;
  title: string;
  image: string;
  alt: string;
  paragraphs: string[];
};

export const scenes: StoryScene[] = [
  {
    number: 1,
    slug: "scene-01",
    title: "Bevor es Oki gab",
    image: "/scenes/scene-01.png",
    alt: "Menschen stehen zwischen Computern, Kabeln und Maschinen und beraten gemeinsam über einen Bauplan.",
    paragraphs: [
      "Bevor es Oki gab, war da nur ein weites Land aus Computern, Kabeln und blinkenden Lichtern.",
      "Auf dem Land standen viele gute Maschinen. Doch jede arbeitete ein wenig anders. Manche kannten sich gut aus. Andere warteten auf Anweisungen. Und wenn jemand eine neue Insel bauen wollte, musste er jedes Mal von vorn überlegen.",
      "Die Menschen schleppten Pläne hin und her.",
      "„Das muss doch auch verlässlicher gehen“, sagte eine Baumeisterin.",
      "Sie legte einen Bauplan auf den Tisch. Darauf stand nicht, welches Lieblingswerkzeug alle benutzen sollten. Darauf stand, was am Ende zuverlässig funktionieren musste.",
      "Dann begann der Boden leise zu brummen.",
    ],
  },
  {
    number: 2,
    slug: "scene-02",
    title: "Oki wird geboren",
    image: "/scenes/scene-02.png",
    alt: "Oki entsteht als freundliche grün-blaue Figur auf einer neuen Insel mit einem Rathaus.",
    paragraphs: [
      "Zwischen den Maschinen leuchteten plötzlich blaue und grüne Linien auf. Sie verbanden sich, ordneten sich und bildeten eine Insel.",
      "Mitten auf der Insel erschien ein Rathaus. In seinen Fenstern flimmerten Karten, Zeichen und freundliche kleine Lichter.",
      "Die neue Insel blinzelte.",
      "„Hallo“, sagte sie. „Ich bin Oki.“",
      "Die Baumeisterinnen und Baumeister lächelten.",
      "Oki sah auf das weite Land, auf die vielen Maschinen und auf seinen eigenen Bauplan. Er freute sich. Aber er tat nicht so, als wüsste er schon alles.",
      "Stattdessen stellte er die Frage, die ihn noch auf viele Abenteuer führen sollte:",
      "„Warum?“",
    ],
  },
  {
    number: 3,
    slug: "scene-03",
    title: "Die Werkstatt und das erste Ei",
    image: "/scenes/scene-03.png",
    alt: "Oki und das Bauteam beobachten in einer Werkstatt ein großes schimmerndes Cluster-Ei mit einem ersten Riss.",
    paragraphs: [
      "Oki bekam eine besondere Werkstatt. Dort konnten auf seinem Boden kleine, sichere Bauplätze entstehen. Jeder Bauplatz hatte Wände, Leitungen und genau die Dinge, die darin gebraucht wurden.",
      "„Das sind noch keine neuen Inseln“, erklärte die Baumeisterin. „Aber hier können sie wachsen.“",
      "Gemeinsam stellten sie ein großes, schimmerndes Ei in die Werkstatt. Auf seiner Schale waren Wünsche notiert: Platz, Verbindungen und ein eigenes Rathaus.",
      "Oki hielt den Atem an.",
      "Im Ei rumpelte es. Erst entstanden Wege und Speicher. Dann begann darin etwas zu erwachen.",
      "Ein feiner Riss erschien auf der Schale.",
      "„Ist es schon fertig?“, fragte Oki.",
      "„Es beginnt erst“, sagte die Baumeisterin.",
    ],
  },
  {
    number: 4,
    slug: "scene-04",
    title: "Wie viele Inseln passen in eine Insel?",
    image: "/scenes/scene-04.png",
    alt: "Auf Okis großer Insel steht eine kleinere Insel mit eigener Grenze, eigenem Rathaus und der blauen Gestalt Mio.",
    paragraphs: [
      "**KNACKS!**",
      "Aus dem Ei kam eine kleine Insel hervor. Sie stand auf Okis Boden und besaß trotzdem einen eigenen Rand, eigene Wege und ein eigenes Rathaus.",
      "Vor dem Rathaus stand eine kleine blaue Gestalt. In ihrer Brust glimmten ein paar verbundene Lichtpunkte. Wenn die Insel sprechen wollte, sprach sie durch diese Gestalt.",
      "Oki lief einmal um sie herum. Dann noch einmal.",
      "„Du bist eine Insel“, sagte er langsam. „Und du stehst auf meiner Insel.“",
      "Die kleine blaue Gestalt nickte stolz.",
      "Oki setzte sich ins Gras und dachte nach.",
      "„Wenn eine Insel in einer Insel wachsen kann“, murmelte er, „wie viele Inseln passen dann eigentlich in eine Insel?“",
      "Niemand kannte die genaue Antwort. Aber alle wussten: Diese Frage würde die Welt viel größer machen.",
    ],
  },
  {
    number: 5,
    slug: "scene-05",
    title: "Mio und ihr eigenes Rathaus",
    image: "/scenes/scene-05.png",
    alt: "Mio steht als kleine blaue Gestalt vor dem eigenen Rathaus; Oki und die Baumeisterin begrüßen die junge Insel.",
    paragraphs: [
      "Vor dem Rathaus stand die kleine blaue Gestalt der jungen Insel. In ihrer Brust leuchtete der kleine blaue Kern aus verbundenen Punkten.",
      "„Technisch heißt du `ok-mgmt`“, sagte die Baumeisterin.",
      "„Das spricht man ok management“, erklärte Oki. „Aber unter Freunden nennen wir dich Mio.“",
      "„Du bist die erste Insel, die auf meinem Boden aus unserem gemeinsamen Bauplan entstanden ist“, sagte Oki. „Mio – meine erste Insel.“",
      "Im Rathaus gab es Tische für Baupläne, Schränke für Regeln und eine große Karte für andere Inseln.",
      "„Soll ich jetzt alle Inseln bauen?“, fragte Mio eifrig.",
      "„Noch nicht“, sagte Oki. „Zuerst lernst du, wie man Verantwortung übernimmt. Andere bauen eine Insel. Dann wird sie dir bewusst vorgestellt. Erst danach hilfst du, gut auf sie aufzupassen.“",
      "Mio dachte kurz nach.",
      "„Kann ich das schon?“",
      "„Wir lernen es gemeinsam“, sagte Oki.",
    ],
  },
  {
    number: 6,
    slug: "scene-06",
    title: "Das Buch der Versprechen",
    image: "/scenes/scene-06.png",
    alt: "Oki zeigt Mio im Rathaus ein großes Buch mit der Aufschrift Verträge – Was muss funktionieren?",
    paragraphs: [
      "Oki brachte ein dickes Buch ins neue Rathaus. Auf dem Umschlag stand:",
      "**VERTRÄGE**\n*Was muss funktionieren?*",
      "„Stehen darin all unsere Lieblingswerkzeuge?“, fragte Mio.",
      "Oki schüttelte den Kopf.",
      "„Werkzeuge können sich ändern. In diesem Buch stehen unsere Versprechen.“",
      "Eine Insel sollte erreichbar sein. Ihre Wege sollten funktionieren. Wichtige Dinge sollten sicher aufbewahrt werden. Und wer sagte, eine Insel sei bereit, sollte es auch zeigen können.",
      "„Versprechen statt Lieblingsbausteine“, las Mio.",
      "„Genau“, sagte Oki. „So können wir bessere Werkzeuge entdecken, ohne jedes Mal die ganze Welt neu zu erfinden.“",
    ],
  },
  {
    number: 7,
    slug: "scene-07",
    title: "Vier neugierige Sensoren",
    image: "/scenes/scene-07.png",
    alt: "Die vier Sensorfiguren Scout, Meter, Check und Proof zeigen Fernglas, Messgerät, Klemmbrett und grünen Haken.",
    paragraphs: [
      "Am nächsten Morgen klopften vier kleine Besucher an die Rathaustür.",
      "Scout trug ein Fernglas. „Kann ich es sehen?“",
      "Meter hielt ein Messgerät hoch. „Was sagt die Messung?“",
      "Check hatte ein Klemmbrett dabei. „Entspricht es dem Versprechen?“",
      "Proof rollte einen großen grünen Haken herein. „Zeig mir den Beweis!“",
      "Mio staunte. „Dann entscheidet ihr also, was wir tun?“",
      "Alle vier schüttelten gleichzeitig den Kopf.",
      "„Wir prüfen Fakten“, sagte Check.",
      "„Wir zeigen, was wahr ist“, ergänzte Proof. „Aber mein grüner Haken ist kein Schlüssel.“",
      "Oki nickte zufrieden. Das war ein wichtiger Unterschied.",
    ],
  },
  {
    number: 8,
    slug: "scene-08",
    title: "Eine neue Insel am Horizont",
    image: "/scenes/scene-08.png",
    alt: "Ein unabhängiges Bauteam baut in der Ferne eine neue Insel, während Oki und Mio sie vom Ufer aus sehen.",
    paragraphs: [
      "Weit hinter Okis Küste arbeitete ein anderes Bauteam. Es kannte das Buch der Versprechen und wollte eine neue Insel für eine Aufgabe bauen.",
      "Das Team zeichnete Wege, bereitete den Boden vor und ließ ein neues Cluster-Ei wachsen.",
      "Nach einer Weile machte es **KNACKS!**",
      "Eine Insel mit eigenem Rathaus erschien am Horizont.",
      "Sie war wirklich da. Sie gehörte aber noch nicht zu Mios Karte.",
      "„Hast du sie gebaut?“, fragte Oki.",
      "Mio schüttelte den Kopf.",
      "„Nein. Das Bauteam hat sie gebaut.“",
      "„Gut beobachtet“, sagte Oki. „Existieren und miteinander verbunden sein sind zwei verschiedene Dinge.“",
    ],
  },
  {
    number: 9,
    slug: "scene-09",
    title: "Darf ich dich vorstellen?",
    image: "/scenes/scene-09.png",
    alt: "Das Bauteam stellt Mio eine bereits bestehende Insel vor; eine bewusste sichere Verbindung erscheint auf Mios Karte.",
    paragraphs: [
      "Das Bauteam kam mit der neuen Insel zu Okis Hafen.",
      "„Wir möchten sie Mio vorstellen“, sagte die Baumeisterin. „Sie soll bewusst Teil der betreuten Inselfamilie werden.“",
      "Mio öffnete nicht einfach heimlich eine Verbindung. Alle prüften gemeinsam, wer die Insel war, welche Versprechen galten und welche Verantwortung übernommen werden sollte.",
      "Dann trugen sie den Namen der Insel in die große Karte ein.",
      "Eine sichere Brücke leuchtete auf.",
      "In Mios Lichtkern erschien ein neuer Punkt. Die neue Insel hatte schon vorher ihr eigenes Licht. Der Punkt zeigte nur: Nun gab es zwischen ihnen eine bewusste Beziehung.",
      "„Willkommen“, sagte Mio. „Jetzt kenne ich dich. Nun können wir dir helfen, die vereinbarten Dinge zu versorgen – und danach prüfen, ob die Versprechen wirklich erfüllt sind.“",
      "Die neue Insel lächelte. Aus einer Begegnung war eine verlässliche Beziehung geworden.",
    ],
  },
  {
    number: 10,
    slug: "scene-10",
    title: "Geboren ist nicht bereit",
    image: "/scenes/scene-10.png",
    alt: "Das Bauteam repariert Wege und Türen auf einer jungen Insel; die Sensoren prüfen danach das Ergebnis und Proof zeigt den Haken.",
    paragraphs: [
      "„Die Insel ist da“, rief Mio. „Dann ist alles fertig!“",
      "Scout sah durch sein Fernglas. Meter betrachtete seine Anzeigen. Check blätterte im Buch. Proof wartete geduldig.",
      "Ein Weg endete noch im Sand. Eine wichtige Tür ließ sich nicht öffnen. Und ein Signal kam nur manchmal an.",
      "„Aber beim Bauen gab es keinen Fehler“, sagte Mio verwundert.",
      "„Ein fertiger Arbeitsschritt ist noch kein fertiges Versprechen“, erklärte Oki.",
      "Das Bauteam kümmerte sich um die fehlenden Dinge. Danach prüften Scout, Meter, Check und Proof noch einmal.",
      "Diesmal hob Proof den grünen Haken.",
      "„Jetzt haben wir nicht nur Hoffnung“, sagte er. „Jetzt haben wir einen Beweis.“",
    ],
  },
  {
    number: 11,
    slug: "scene-11",
    title: "Der Leuchtturm",
    image: "/scenes/scene-11.png",
    alt: "Ein hoher Leuchtturm beleuchtet mehrere Inseln und macht eine dunkle Stelle auf einer Brücke sichtbar.",
    paragraphs: [
      "Mit jeder neuen Insel wurde das Meer unübersichtlicher. Also bauten die Freunde einen hohen Leuchtturm.",
      "Sein Licht zeigte, welche Insel gut erreichbar war, wo ein Weg langsam wurde und wo plötzlich etwas fehlte.",
      "„Verhindert der Leuchtturm alle Probleme?“, fragte Mio.",
      "„Nein“, sagte Oki. „Aber er hilft uns, sie zu sehen.“",
      "In derselben Nacht entdeckte der Lichtstrahl eine dunkle Stelle auf einer Brücke. Der Leuchtturm reparierte sie nicht. Er zeigte den Freunden nur genau, wo sie hinschauen mussten.",
      "„Sehen ist nicht dasselbe wie handeln“, sagte Mio.",
      "„Aber ohne Sehen handeln wir im Dunkeln“, antwortete Oki.",
    ],
  },
  {
    number: 12,
    slug: "scene-12",
    title: "Aia und der Rucksack voller Ideen",
    image: "/scenes/scene-12.png",
    alt: "Aia landet mit einem kleinen Luftschiff und einem violetten Rucksack voller Pläne und Ideen bei Oki und Mio.",
    paragraphs: [
      "Eines Tages landete ein kleines Luftschiff am Hafen. Heraus sprang Aia. Auf ihrem Rücken trug sie einen violetten Rucksack, der verdächtig voll aussah.",
      "„AIA bedeutet AI Agent“, erklärte sie. „Aber nennt mich einfach Aia.“",
      "Sie konnte schnell lesen, viele Hinweise vergleichen und auf der Inselkarte nach ungewöhnlichen Dingen suchen.",
      "Schon bald entdeckte sie, dass ein Weg anders verlief als im Buch der Versprechen.",
      "„Ich hätte da eine Idee“, sagte Aia und zog drei Pläne, zwei Listen und noch eine überraschend große Rolle Papier aus ihrem Rucksack.",
      "„Sehr gut“, sagte Oki. „Dann prüfen wir deine Idee gemeinsam.“",
    ],
  },
  {
    number: 13,
    slug: "scene-13",
    title: "Das Tor und der Schlüssel",
    image: "/scenes/scene-13.png",
    alt: "Aia, Oki und die Sensoren stehen vor einem Tor; die menschliche Baumeisterin hält den Entscheidungsschlüssel.",
    paragraphs: [
      "Aias Plan, das Buch und die Ergebnisse der Sensoren lagen vor einem großen Tor. Hinter dem Tor konnte aus einem Vorschlag eine wirkliche Veränderung werden.",
      "Aia suchte in ihrem Rucksack.",
      "„Wo ist denn der Schlüssel?“",
      "Die Baumeisterin hob ihn hoch.",
      "„Bei mir.“",
      "„Weil du mir nicht vertraust?“, fragte Aia.",
      "„Doch“, sagte die Baumeisterin. „Gerade deshalb geben wir jedem eine klare Aufgabe. Du hilfst uns beim Denken. Die Sensoren prüfen Fakten. Und Menschen tragen die Verantwortung für die Entscheidung.“",
      "Gemeinsam lasen sie den Plan, stellten Fragen und verbesserten eine Stelle. Dann drehte die Baumeisterin den Schlüssel um.",
      "Das Tor öffnete sich.",
    ],
  },
  {
    number: 14,
    slug: "scene-14",
    title: "Die Familie der vielen Inseln",
    image: "/scenes/scene-14.png",
    alt: "Oki, Mio und Aia betrachten eine vielfältige Familie aus Versorgungs-, KI-, Robotik- und IoT-Inseln.",
    paragraphs: [
      "Nach und nach lernte Oki viele verschiedene Inseln kennen.",
      "Da war der Versorgungshafen `ok-shared` mit Tresor, Lagerhaus, Speicher und Leuchtturm. Auf `ok-ai` tüftelten Menschen an hilfreichen Maschinen. Auf `ok-robotics` bewegten sich Roboter über sichere Wege. Und von `ok-iot` sendeten kleine Geräte Nachrichten aus weit entfernten Gegenden.",
      "Jede Insel hatte eine andere Aufgabe. Jede hatte ihr eigenes Rathaus. Und alle konnten dieselben wichtigen Versprechen verstehen.",
      "„Müssen sie dafür gleich aussehen?“, fragte Aia.",
      "„Nein“, sagte Oki. „In einer Familie darf jeder anders sein. Sie hält zusammen, weil sich alle aufeinander verlassen können.“",
    ],
  },
  {
    number: 15,
    slug: "scene-15",
    title: "Okis Inselwelt für den Rucksack",
    image: "/scenes/scene-15.png",
    alt: "Oki, Aia und Kinder probieren auf einem Laptop eine kleine Inselwelt zum Lernen und Experimentieren aus.",
    paragraphs: [
      "Viele Menschen wollten die Inselwelt kennenlernen. Aber nicht alle hatten ein weites Land voller großer Maschinen.",
      "Also bauten Oki und seine Freunde eine kleine Übungswelt. Sie passte auf einen Laptop und reiste sogar in einem Rucksack mit.",
      "Sie nannten sie `ok-local`.",
      "Dort konnten Neugierige Inseln entstehen lassen, Rathäuser entdecken, Versprechen ausprobieren und Fehler machen, ohne eine echte Hafenstadt in Gefahr zu bringen.",
      "„Ist das eine ganz normale Produktionsinsel?“, fragte Aia.",
      "„Nein“, sagte Oki. „Es ist ein Ort zum Lernen und Ausprobieren.“",
      "Aia stopfte noch ein Notizbuch in ihren Rucksack. Nun war er endgültig zu voll.",
    ],
  },
  {
    number: 16,
    slug: "scene-16",
    title: "Der große Sturm",
    image: "/scenes/scene-16.png",
    alt: "Nach einem Sturm bauen Menschen Mios Rathaus und Grundwege aus gesicherten Plänen wieder auf; andere Inseln leuchten weiter.",
    paragraphs: [
      "Dann kam der Sturm.",
      "Wind riss an den Brücken, Wellen schlugen gegen Mios Rathaus und die große Karte wurde dunkel. Auch Mios blauer Lichtkern erlosch. Doch die anderen Inseln leuchteten weiter.",
      "Oki blieb der feste Anker außerhalb der jungen Insel.",
      "Die Menschen holten die aufbewahrten Baupläne hervor und bauten Rathaus und wichtige Grundwege neu. Doch nicht alles stand in diesen Plänen. Manche Beziehungen, Zugänge und Erinnerungen mussten aus ihren eigenen sicheren Orten zurückgebracht werden.",
      "Als das Licht zurückkehrte, atmeten alle auf.",
      "Doch Mio sah sich um. „Ist nun auch jede Erinnerung genauso zurück wie vorher?“",
      "Oki antwortete ehrlich: „Ein Bauplan kann uns helfen, dich wieder aufzubauen. Erinnerungen müssen wir aber ebenfalls bewusst sichern und wiederherstellen.“",
      "Von da an verwechselten sie Wiederaufbau nie wieder mit vollständigem Gedächtnis.",
    ],
  },
  {
    number: 17,
    slug: "scene-17",
    title: "Die nächste Generation",
    image: "/scenes/scene-17.png",
    alt: "Menschen, Oki und Mio betrachten einen klar mit Morgen markierten Zielplan für einen zukünftigen Cluster-Lebenszyklus.",
    paragraphs: [
      "Eines Tages zeigte Oki Mio einen besonderen Bauplan. Oben darauf stand groß: **MORGEN**.",
      "Auf diesem Plan sollte Mio eines Tages neue Inseln von Anfang an begleiten – vom ersten Ei bis zur geprüften Insel.",
      "Mio erinnerte sich an seine erste Frage: „Kann ich das schon?“",
      "Diesmal sah es lange auf den Plan und sagte:",
      "„Dafür bin ich verantwortlich.“",
      "„Und ich mache das nicht allein“, ergänzte Mio. „Ich helfe, dass aus einem guten Plan eine verlässliche Insel wird.“",
      "„Noch ist das unser Ziel“, sagte Oki. „Aber gute Ziele beginnen mit einem klaren Versprechen.“",
      "Eines Morgens erschien am Strand ein neues Cluster-Ei.",
      "Daneben wartete ein junger Cluster und betrachtete es unsicher.",
      "„Kann ich das schon?“, fragte er.",
      "Mio erinnerte sich an seine ersten Tage. Es stellte sich neben ihn, nicht vor ihn.",
      "„Du musst nicht alles allein wissen“, sagte es. „Wir haben Baupläne, Versprechen, Sensoren und Menschen, die Verantwortung übernehmen.“",
      "Im Ei begann es leise zu klopfen.",
      "Mio lächelte.",
      "„Wenn du bereit bist, hilfst du später der nächsten Insel beim Entstehen.“",
    ],
  },
  {
    number: 18,
    slug: "scene-18",
    title: "Welche Insel ist OpenKubes?",
    image: "/scenes/scene-18.png",
    alt: "Oki, Mio und Aia blicken am Abend über eine vielfältige, leuchtende Familie vieler Inseln.",
    paragraphs: [
      "Am Abend standen alle auf dem höchsten Hügel. Unter ihnen leuchteten viele Inseln: große und kleine, nahe und ferne, ruhige und geschäftige.",
      "Der junge Cluster zeigte erst auf Oki, dann auf Mio und schließlich auf die ganze Inselfamilie.",
      "„Welche Insel davon ist OpenKubes?“",
      "Oki lächelte.",
      "„Nicht eine einzige.“",
      "Er schlug das Buch der Versprechen auf.",
      "„OpenKubes ist eine gute Art, immer wieder verlässliche Inseln zu bauen.“",
      "Die Freunde blickten über das Meer.",
      "**Baue. Verbinde. Prüfe. Lerne. Wachse.**",
      "Irgendwo in der Ferne hörten sie ein leises Geräusch.",
      "**knacks ...**",
    ],
  },
];
